export const clientes = [
  {
    id: 1,
    nome: "Construtora Amazônia LTDA",
    cnpj: "12.345.678/0001-90",
    responsavel: "Carlos Silva",
    telefone: "(91) 98765-4321",
    email: "carlos@amazoniaconstru.com",
    endereco: "Rod. BR-316, km 12, Ananindeua - PA",
    cidade: "Ananindeua",
    servico: "Limpeza de banheiros químicos",
  },
  {
    id: 2,
    nome: "Mineração Norte Verde",
    cnpj: "98.765.432/0001-12",
    responsavel: "Juliana Costa",
    telefone: "(91) 99876-1234",
    email: "juliana@norteverde.com.br",
    endereco: "Fazenda Mineral, Zona Rural, Parauapebas - PA",
    cidade: "Parauapebas",
    servico: "Coleta de efluentes sanitários",
  },
  {
    id: 3,
    nome: "Engenharia Pará Obras",
    cnpj: "11.222.333/0001-44",
    responsavel: "Marcelo Andrade",
    telefone: "(91) 98567-8910",
    email: "marcelo@engparaobras.com",
    endereco: "Av. Perimetral, 1023, Belém - PA",
    cidade: "Belém",
    servico: "Limpeza de banheiros químicos",
  },
  {
    id: 4,
    nome: "Eventos Top Norte",
    cnpj: "00.111.222/0001-55",
    responsavel: "Aline Rocha",
    telefone: "(91) 98456-7890",
    email: "aline@topnorteeventos.com",
    endereco: "Rua das Mangueiras, 456, Castanhal - PA",
    cidade: "Castanhal",
    servico: "Limpeza de banheiros químicos",
  },
  {
    id: 5,
    nome: "Terraplanagem Solimões",
    cnpj: "99.888.777/0001-66",
    responsavel: "Rogério Matos",
    telefone: "(91) 98712-3456",
    email: "rogerio@solimoes.com",
    endereco: "Rua Projetada, 321, Marabá - PA",
    cidade: "Marabá",
    servico: "Coleta de efluentes sanitários",
  },
  {
    id: 6,
    nome: "Hidrosan Obras e Serviços",
    cnpj: "88.777.666/0001-77",
    responsavel: "Fernanda Lima",
    telefone: "(91) 99234-5678",
    email: "fernanda@hidrosan.com",
    endereco: "Travessa Tucunaré, 89, Altamira - PA",
    cidade: "Altamira",
    servico: "Coleta de efluentes sanitários",
  },
  {
    id: 7,
    nome: "BioEventos Pará",
    cnpj: "77.666.555/0001-88",
    responsavel: "Eduardo Tavares",
    telefone: "(91) 98123-4567",
    email: "eduardo@bioeventos.com",
    endereco: "Av. das Palmeiras, 200, Abaetetuba - PA",
    cidade: "Abaetetuba",
    servico: "Limpeza de banheiros químicos",
  },
  {
    id: 8,
    nome: "Obras Forte Norte",
    cnpj: "66.555.444/0001-99",
    responsavel: "Tatiane Alves",
    telefone: "(91) 98345-6789",
    email: "tatiane@obrasforte.com",
    endereco: "Rod. PA-150, km 45, Tailândia - PA",
    cidade: "Tailândia",
    servico: "Coleta de efluentes sanitários",
  },
  {
    id: 9,
    nome: "Construtora Tapajós",
    cnpj: "55.444.333/0001-00",
    responsavel: "Ricardo Lima",
    telefone: "(91) 98678-1234",
    email: "ricardo@tapajosconstrutora.com",
    endereco: "Rua dos Trabalhadores, 1001, Santarém - PA",
    cidade: "Santarém",
    servico: "Limpeza de banheiros químicos",
  },
  {
    id: 10,
    nome: "EcoSoluções Ambientais",
    cnpj: "44.333.222/0001-11",
    responsavel: "Marina Duarte",
    telefone: "(91) 98234-9876",
    email: "marina@ecosolucoes.com",
    endereco: "Estrada da Liberdade, 2100, Barcarena - PA",
    cidade: "Barcarena",
    servico: "Coleta de efluentes sanitários e limpeza de banheiros químicos",
  },
];
